### ISSUE TITLE
Quantcast broke builds by using non-specific versions of Google Play Services

### ISSUE THREAD

**Issue by dlew** [quantcast/android-measurement#12]
Here's the situation:

1. Our app is using `com.google.android.gms:play-services-wearable:6.5.87`, which depends on `com.google.android.gms:play-services-base:6.5.87`.
1. Our app is also using `com.quantcast.android.measurement:QuantcastAndroidSdk-split:1.2.6`, which depends on `com.google.android.gms:play-services-base:+` (but does not include the wearable split).
1. `com.google.android.gms:play-services-wearable:6.5.87` is not source compatible with `com.google.android.gms:play-services-base:7.0.0`

Since Gradle uses the most recent version for any dependency, this meant that Quantcast (since it didn't care which version it used) would pull in `base:7.0.0`, but we'd still be using `wearable:6.5.87`. As a result, our code stopped compiling even though we had made *no* changes to the code.

Quantcast should *not* be using a general selector. It should be tied to a specific version of Google Play Services so that this sort of problem doesn't happen.

**Comment by dlew** [comment]
To be a bit more specific: It looks like the root cause is `com.google.android.gms:play-services-ads:+`, which then depends on `com.google.android.gms:play-services-base`.

**Comment by SmithKevin** [comment]
Hi dlew,
   Thanks for letting us know.    I took a look at our maven pom file and the requirement in there is for play-services-ads:6.5.  I see this on both the maven central and bintray repositories.  Where exactly do you see it set to com.google.android.gms:play-services-ads:+ ?  It's possible that some wrong configuration slipped through somewhere.  Thanks for the help in tracking this down.
-Kevin

**Comment by dlew** [comment]
I'm going off of what gradle's dependencyInsight is telling me:

```
$ gradle -q :trello-app:dependencyInsight --dependency play-services-base --configuration compile

com.google.android.gms:play-services-base:7.0.0 (conflict resolution)
+--- com.google.android.gms:play-services-ads:7.0.0
|    \--- com.quantcast.android.measurement:QuantcastAndroidSdk-split:1.2.6
|         \--- compile
\--- com.google.android.gms:play-services-analytics:7.0.0
     \--- com.google.android.gms:play-services-ads:7.0.0 (*)

com.google.android.gms:play-services-base:6.5.87 -> 7.0.0
+--- project :submodules:snowman:library
|    \--- compile
+--- compile
+--- com.google.android.gms:play-services-drive:6.5.87
|    \--- compile
+--- com.google.android.gms:play-services-identity:6.5.87
|    \--- compile
\--- com.google.android.gms:play-services-wearable:6.5.87
     \--- compile

(*) - dependencies omitted (listed previously)
```

**Comment by dlew** [comment]
And I opened up the Quantcast POM to find an open-ended version:

```
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-ads</artifactId>
      <version>[6.5,)</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by dlew** [comment]
That means my initial analysis is wrong; it's not just using +. But it's using the range `[6.5,)` which means *any* version above 6.5.

**Comment by SmithKevin** [comment]
Interesting.  OK I'll find some time today to look into this further.  The main reason we left it open ended is because we didn't want the opposite of your situation to occur.   If someone upgrades to 7.0 then we would still be causing a conflict and we didn't want to have to re-release for every version upgrade.    I remember reading something about dependency conflict handling in Gradle.   Since our SDK only depends on >6.5, there should be a way to force the dependency back down to 6.5 as opposed to using the latest.    I'll let you know what I find.   Worst case I'll fix the POM and re-release.   Thanks again for the help.

**Comment by dlew** [comment]
> If someone upgrades to 7.0 then we would still be causing a conflict and we didn't want to have to re-release for every version upgrade.

That's not true; If someone else upgrades to 7.0, then your library will use 7.0 as well due to the same conflict resolution that led our main project to use 7.0 instead of 6.5.

You *will* have to release a new version of the SDK if GMS updates in a source-incompatible way anyways. If GMS 8.0 changes the method signature for some method your library is using, then using the open-ended range will result in using 8.0 but then failing to build every time.

**Comment by SmithKevin** [comment]
Sorry this has taken a while, but I found some time to look into the issue further.  So you can fix the issue by forcing the use of a lower version of `play-service-ads` which in turn will force the base library down as well.    
```
    compile('com.google.android.gms:play-services-ads:6.5.87') {
       force = true
    }
```
Let me know if that fixes your issue for the time being.

**Comment by dlew** [comment]
Another new version of Google Play Services, another time that Quantcast has broken our builds. Why not just release a non-ranged version of this plugin?

**Comment by SmithKevin** [comment]
Hi Daniel,
    Thanks for bringing this our attention.   Just curious if you had a chance to try the fix I posted earlier?  Does that not work for your project?

**Comment by dlew** [comment]
It's a bandaid, treating the symptom instead of the cause, and I don't want to have to maintain it. We don't use GPS ads in our app *except* through Quantcast so there's no reason for us to have to define it as a dependency. The correct fix would be the Quantcast SDK fixing its ranged dependency.

**Comment by SmithKevin** [comment]
Sorry for the delayed response.   Got pulled elsewhere for a bit.  Personally, I think a open-ended dependency is the way to go in order to keep the SDK compatible for everyone without us having to re-deploy a new SDK for every google play version.  There is no magic bullet for dependency management in Gradle.  Instead it should be up to the project owner to have a robust conflict resolution strategy to be sure you are explicitly getting what you expect and you don't have to rely on other people.  For example, in your case since you want to use an older version of the Google Play Services you could add the following to your build.gradle project:
```
configurations.all {
    resolutionStrategy {
        //being proactive about conflicts
        failOnVersionConflict()
        eachDependency { DependencyResolveDetails details ->
            //specifying a fixed version for all Google Play libraries
            if (details.requested.group == 'com.google.android.gms') {
                details.useVersion '6.5.87'
            }
        }
    }
}
```
Basically telling the system that no matter what the transitive dependancies, you only want the Play Service libraries of 6.5.87.  It could break a dependency that doesn't support that version, but it wasn't going to work with the app anyway so no big difference and you can still track issues with the dependency insight tool.  Now if one day you wanted to move to a different version, you change this rule and everything just moves forward.

That being said, I understand everyones project is set up differently so that might not work for everyone.  So I also made the requested fixed version library.  That way if you don't want to or it's not possible to maintain any additional code in your build file, you don't have to.   The new fixed version is here:
`compile 'com.quantcast.android.measurement:QuantcastAndroidSdk-split:1.2.7_6x'`

Please let me know if you have any other issues.

**Comment by yairkukielka** [comment]
I'm having a similar issue. GPS 7.5.0 and GPS 7.8.0 both depend on support-v4 library version 22.0.0. I'm trying to use support-v4 library version 22.2.1 and GPS 7.5.0, but this generates a conflict with the GPS dependency of Quantcast. 

I'm doing this so I control the GPS version that I want to use. Do you think this could be added to your docs?

compile 'com.google.android.gms:play-services-base:7.5.0'
compile ('com.quantcast.android.measurement:QuantcastAndroidSdk-split:1.3.+') {
        exclude group: 'com.google.android.gms'
    }
